default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tb7
  password: password

development:
  <<: *default
  database: daily_drift_development

test:
  <<: *default
  database: daily_drift_test

production:
  <<: *default
  database: daily_drift_production
  username: tb7
  password: <%= ENV['DAILY_DRIFT_DATABASE_PASSWORD'] %>
